language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis codecov

script:
  - tox -vv

matrix:
  include:
    - python: 3.7
      env: TOXENV=docs


## Could we deploy to GH pages with this?

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
    condition: "$TOXENV == docs"
  local_dir: docs/build/html/

after_success:
  - codecov
