language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis codecov

script:
  - tox -vv

matrix:
  include:
    - python: 3.7
      env: TOXENV=docs
    #- os : windows
    #  # https://blog.travis-ci.com/2018-10-11-windows-early-release
    #  language : shell
    #  python: "3.6"
    #  env: TOXENV=py36
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6
        - python3 --version
        - python3 -m pip install --upgrade pip
      python: "3.6"
      env: TOXENV=py36

after_success:
  - codecov
