dist: xenial

language: python

python:
  - "3.7"
  - '3.6'
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gcc libffi-dev python3-dev

install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
  - pip install -e .

script:
  - pytest --cov-report term --cov=fibonacci/tests

after_success:
  - codecov