language: python

python:
  - "3.6"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  
install:
  - pip install '.[test]' . # install our package and test dependencies.

script:
  - pytest
